// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SwaggerApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MusicFestival
    {
        /// <summary>
        /// Initializes a new instance of the MusicFestival class.
        /// </summary>
        public MusicFestival() { }

        /// <summary>
        /// Initializes a new instance of the MusicFestival class.
        /// </summary>
        public MusicFestival(string name = default(string), IList<Band> bands = default(IList<Band>))
        {
            Name = name;
            Bands = bands;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bands")]
        public IList<Band> Bands { get; set; }

    }
}
